# Generated by Django 3.2.9 on 2021-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddHostel',
            fields=[
                ('Hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hostel_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AddMess',
            fields=[
                ('Mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('Mess_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('HostelName', models.CharField(max_length=20)),
                ('MessName', models.CharField(max_length=20)),
            ],
        ),
    ]
