from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^index$', views.index),
    url(r'^adminlogin$', views.adminlogin),
    url(r'^studentlogin$', views.studentlogin),
    url(r'^studentregister$', views.studentregister),
    url(r'^adminhome$', views.adminhome),
    url(r'^studentdetails$', views.studentdetails),
    url(r'^addhostel$', views.addhostel),
    url(r'^addmess$', views.addmess),
    url(r'^studentfeedback$', views.studentfeedback),
    url(r'^studenthome$', views.studenthome),
    url(r'^hosteldetails$', views.hosteldetails),
    url(r'^feedetails$', views.feedetails),
    url(r'^messdetails$', views.messdetails),
    url(r'^addfeedback$', views.addfeedback),
    url(r'^StudentSignup$', views.StudentSignup),
    url(r'^StudentSignin$', views.StudentSignin),
    url(r'^StudentLogout$', views.StudentLogout),
    url(r'^AdminSignin$', views.AdminSignin),
    url(r'^AdminLogout$', views.AdminLogout),
    url(r'^AddHostels$', views.AddHostels),
    url(r'^AddMesses$', views.AddMesses),
    url(r'^showhostels$', views.showhostels),
    url(r'^showmesses$', views.showmesses),
    url(r'^deletehostel/(?P<Hostel_id>\d+)$', views.deletehostel),
    url(r'^deletemess/(?P<Mess_id>\d+)$', views.deletemess),
    url(r'^registerhostel$', views.registerhostel),
    url(r'^alreadyregisteredid$', views.alreadyregisteredid),
    url(r'^searcheddetails$', views.searcheddetails),
    url(r'^search$', views.search),
    url(r'^messsearched$', views.messsearched),
    url(r'^searchmess$', views.searchmess),
    url(r'^addfeedback$', views.addfeedback),
    url(r'^aboutpage$', views.aboutpage),
]